/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsToolSlugRouteImport } from './routes/tools.$toolSlug'
import { Route as CheckoutToolSlugRouteImport } from './routes/checkout.$toolSlug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolSlugRoute = ToolsToolSlugRouteImport.update({
  id: '/$toolSlug',
  path: '/$toolSlug',
  getParentRoute: () => ToolsRoute,
} as any)
const CheckoutToolSlugRoute = CheckoutToolSlugRouteImport.update({
  id: '/checkout/$toolSlug',
  path: '/checkout/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/checkout/$toolSlug': typeof CheckoutToolSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/checkout/$toolSlug': typeof CheckoutToolSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/checkout/$toolSlug': typeof CheckoutToolSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/integrations'
    | '/marketplace'
    | '/privacy'
    | '/refunds'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/checkout/$toolSlug'
    | '/tools/$toolSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/integrations'
    | '/marketplace'
    | '/privacy'
    | '/refunds'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/checkout/$toolSlug'
    | '/tools/$toolSlug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/integrations'
    | '/marketplace'
    | '/privacy'
    | '/refunds'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/checkout/$toolSlug'
    | '/tools/$toolSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DocsRoute: typeof DocsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  CheckoutToolSlugRoute: typeof CheckoutToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolSlug': {
      id: '/tools/$toolSlug'
      path: '/$toolSlug'
      fullPath: '/tools/$toolSlug'
      preLoaderRoute: typeof ToolsToolSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/checkout/$toolSlug': {
      id: '/checkout/$toolSlug'
      path: '/checkout/$toolSlug'
      fullPath: '/checkout/$toolSlug'
      preLoaderRoute: typeof CheckoutToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteChildren {
  ToolsToolSlugRoute: typeof ToolsToolSlugRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsToolSlugRoute: ToolsToolSlugRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DocsRoute: DocsRoute,
  IntegrationsRoute: IntegrationsRoute,
  MarketplaceRoute: MarketplaceRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  CheckoutToolSlugRoute: CheckoutToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
