/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsToolSlugRouteImport } from './routes/tools.$toolSlug'
import { Route as CheckoutToolSlugRouteImport } from './routes/checkout.$toolSlug'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories.$categoryId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolSlugRoute = ToolsToolSlugRouteImport.update({
  id: '/$toolSlug',
  path: '/$toolSlug',
  getParentRoute: () => ToolsRoute,
} as any)
const CheckoutToolSlugRoute = CheckoutToolSlugRouteImport.update({
  id: '/checkout/$toolSlug',
  path: '/checkout/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => CategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/checkout/$toolSlug': typeof CheckoutToolSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/checkout/$toolSlug': typeof CheckoutToolSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/checkout/$toolSlug': typeof CheckoutToolSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/contact'
    | '/docs'
    | '/integrations'
    | '/marketplace'
    | '/sitemap.xml'
    | '/tools'
    | '/categories/$categoryId'
    | '/checkout/$toolSlug'
    | '/tools/$toolSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/contact'
    | '/docs'
    | '/integrations'
    | '/marketplace'
    | '/sitemap.xml'
    | '/tools'
    | '/categories/$categoryId'
    | '/checkout/$toolSlug'
    | '/tools/$toolSlug'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/contact'
    | '/docs'
    | '/integrations'
    | '/marketplace'
    | '/sitemap.xml'
    | '/tools'
    | '/categories/$categoryId'
    | '/checkout/$toolSlug'
    | '/tools/$toolSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  CheckoutToolSlugRoute: typeof CheckoutToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolSlug': {
      id: '/tools/$toolSlug'
      path: '/$toolSlug'
      fullPath: '/tools/$toolSlug'
      preLoaderRoute: typeof ToolsToolSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/checkout/$toolSlug': {
      id: '/checkout/$toolSlug'
      path: '/checkout/$toolSlug'
      fullPath: '/checkout/$toolSlug'
      preLoaderRoute: typeof CheckoutToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof CategoriesRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface ToolsRouteChildren {
  ToolsToolSlugRoute: typeof ToolsToolSlugRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsToolSlugRoute: ToolsToolSlugRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  IntegrationsRoute: IntegrationsRoute,
  MarketplaceRoute: MarketplaceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsRoute: ToolsRouteWithChildren,
  CheckoutToolSlugRoute: CheckoutToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
